config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   get 'new'=>'location#new'
  get 'index'=>'location#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
has_many :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def poisk 
@locations = Location.where("name LIKE?", "%#{value_for_search}%")
end

def new
@location = Location.new
end 

def index
    @locations = Location.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Userloc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/location/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Locations</h1>

<div class="locations">
  <div class="form-group">
    <label for="exampleInputEmail1">Name</label>
  </div>

  
    <% @locations.each do |location| %>
    <div class="form-group">
      <p><%= location.name %></p>
       <%= link_to 'Show', location, class: 'btn btn-outline-primary' %>
         
        <%= link_to 'Edit', edit_location_path(location), class: 'btn btn-outline-primary' %>
          
        <%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-outline-primary' %>\
        
      
        </div>
    <% end %>

<%= link_to "Search", poisk_location_path , class="form-control form-control-sm" type="text" %>
  
  <%= link_to "New Location", new_location_path , class: 'btn btn-outline-success' %>
  </div>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" href="projects.scss"></link>

app/views/location/new.html.erb
<div class="forms">
  <%= render 'form', location: @location %>
</div>
<div class="links">
  <%= link_to 'Back', locations_path %>
</div>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  